### ISSUE TITLE
Plugin fails to start correctly

### ISSUE THREAD

**Issue by jvnni** [nparashuram/cordova-plugin-browsersync#15]
After running `cordova run ios -- --live-reload` brower-sync seems to start ok but right after an error is logged and the server fails to start.

```
[xmldom error]  element parse error: Error: invalid tagName:^���Y�-
@#[line:4,col:107]
Error: Cannot read property 'nodeName' of null
```

<img width="770" alt="screen shot 2016-04-17 at 01 37 55" src="https://cloud.githubusercontent.com/assets/437205/14585093/9439550e-043d-11e6-94a6-9c71104117cd.png">

**Comment by axemclion** [comment]
@jvnni looks like there was an unknown tag in the plist file. Can you paste your plist file here ?

P.S: I love the high resolution screenshot :)

**Comment by Argurth** [comment]
Hi ! Get a similar problem, to got it working, I must remove ios from the cordova platforms
It's not a problem for developpement, I can develop on android only, and then, re-add ios but it's quite annoying because I have to reconfigure some xcode stuff each time I want to build my app
Could you look into it ? :)

PS : Here is a screenshot
![capture d ecran 2016-04-30 a 19 57 24](https://cloud.githubusercontent.com/assets/4427644/14937637/5b74a4e0-0f0e-11e6-8e6a-534c76cb069c.png)

**Comment by rburgst** [comment]
Have the same problem. It seems that this is caused by the patcher going too far and also scanning files in the `platforms/ios/HelloCordova.xcarchive/` folder. These are binary plist files which cannot be parsed by the plain text xml parser.
